#ifndef __KERNEL_CONF_H__
#define __KERNEL_CONF_H__

/* This file is auto-generated by CMake and scripts under conf/ */

#define KERNEL_BUILD_NAME               "tinyKern"
#define KERNEL_BUILD_VERSION            "0.0.2"
#define KERNEL_BUILD_TARGET             "AARCH64_VIRT"
#define KERNEL_BUILD_STYLE              "DEBUG"
#define KERNEL_SOURCE_VERSION           "tinykern-0200.142.12.3"

#endif /* __kernel_conf_h__ */